version: '3.7'
services:
    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
#            - "${PWD}/db-data:/var/lib/postgresql/data"
            - "/var/lib/postgresql/data"

    local-runner:
        image: 658443672529.dkr.ecr.us-east-1.amazonaws.com/amazon/mwaa-local:2.2.2
        build: .
        restart: always
        depends_on:
            - postgres
        env_file:
            - aws_config
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_AWS_DATA_PLANE=aws://?role_arn=arn%3Aaws%3Aiam%3A%3A796406704065%3Arole%2FCrossAccountRole-658443672529&region_name=us-east-1&external_id=Rearc-Data-Platform-658443672529
            - AIRFLOW_CONN_AWS_DEFAULT=aws://?region_name=us-east-1&role_arn=arn%3Aaws%3Aiam%3A%3A658443672529%3Arole%2Fservice-role%2Fairflow-rearc-data-platform-MwaaExecutionRole-165NIXZ70SXEE
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${DAG_DIR:-./dags}:/usr/local/airflow/dags
            - ${PWD}/plugins:/usr/local/airflow/plugins
            - ~/.aws:/usr/local/airflow/.aws:ro
        ports:
            - "8080:8080"
        command: local-runner
        tmpfs:
            - /tmp
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
