version: '3.7'
services:
    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
#            - "${PWD}/db-data:/var/lib/postgresql/data"
            - "/var/lib/postgresql/data"

    local-runner:
#        image: 658443672529.dkr.ecr.us-east-1.amazonaws.com/amazon/mwaa-local:2.2.2
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - DAG_ECS_TAG_PREFIX=${TAG_PREFIX}
            - AWS_PROFILE=${AWS_PROFILE}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${DAG_DIR:-./dags}:/usr/local/airflow/dags
            - ${PWD}/plugins:/usr/local/airflow/plugins
            - ~/.aws:/usr/local/airflow/.aws:ro
        ports:
            - "8080:8080"
        command: local-runner
        tmpfs:
            - /tmp
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
