---
version: '3.7'

networks:
  rearc_data_platform_nw:
    # Use a custom name
    name: rearc_data_platform_nw
    external: true
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      # - "${PWD}/db-data:/var/lib/postgresql/data"
      - "/var/lib/postgresql/data"
    networks:
      - rearc_data_platform_nw

  local-runner:
    # image: amazon/mwaa-local:2_7
    # platform: "linux/amd64"
    # platform: "linux/arm64"
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      # Environment
      LOAD_EX: n
      EXECUTOR: Local
      AWS_PROFILE: ${AWS_PROFILE}
      MWAA_IS_LOCAL: ${RUN_LOCAL:-1}
      REQUIREMENTS_FILE: dags/requirements.txt
      # Overrides for airflow.cfg
      AIRFLOW__SECRETS__BACKEND_KWARGS: '{"connections_prefix": "/${DEPLOYMENT:-dev}/airflow/connections", "variables_prefix": "/${DEPLOYMENT:-dev}/airflow/variables"}'
      AIRFLOW__RDP__BLOB: "${RDP_CONFIG}"
      AIRFLOW__SENTRY__ON: "False"
      # Overrides for DagConfig
      DAG__ECS__TAG_PREFIX: ${TAG_PREFIX}
      DAG__SENTRY__ENVIRONMENT: user_local
      DAG__SENTRY__DISABLED: "true"
      DAG__PREFECT__LOCAL_API: "http://orion_server:4200/api"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${DAG_DIR:-./dags}:/usr/local/airflow/dags"
      - "${PLUGINS_DIR:-./plugins}:/usr/local/airflow/plugins"
      # - "${PWD}/requirements:/usr/local/airflow/requirements"
      - "${PWD}/startup_script:/usr/local/airflow/startup"
      - ~/.aws:/usr/local/airflow/.aws:ro
      - ~/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/airflow/.cache/pip
      - /root/.cache/pip
    ports:
      - "8080:8080"
    command: local-runner
    user: root
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./config/.env.localrunner
    networks:
      - rearc_data_platform_nw